### ISSUE TITLE
Tracking issue for cleanup of runtime

### ISSUE THREAD

**Issue by stanly-johnson** [valibre-org/vln-node#107]
Many pallets/functions are no longer required since the core focus is now shifted to a `parachain for on/off ramp`, removing this will reduce the build times/size

Pallets that can be removed/refactored

- [ ] Human swap (remove - replaced by escrow)
- [ ] Backed Asset (can be removed 🤔 )
- [ ] Foreign Asset (can be removed 🤔 )
- [ ] Transfers (can be removed 🤔 )

**Comment by olanod** [comment]
Agree, the backed asset and transfers can be removed, the foreign assets one as well which I think it can just be an instant of substrate assets' pallet used solely for fiat assets and already comes with the functionality to create tokens in a permissionless way with a deposit. Human swap is more of a protocol than just a pallet now, its spiritual successor aside from the escrow might be the need to revamp the rates pallet to not just give a rate without context but to say specifically _"this amount of fiat asset A that I'm reserving/locking, I would change it for X amount of B transferable with medium M"_, but then if we later are also adding logic of a "rate agreement" to track the rate two parties agreed on for a swap we are kind of reviving the Human swap pallet altogether 😅 For now let's keep assuming the value of the escrow has the right rate and that there's no need for an on-chain agreement of the price.
